--------------------------------------------------------
--  File created - Monday-February-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "JUNIT"."EMPLOYEE" 
   (	"CRMD" VARCHAR2(10 BYTE), 
	"AMBIENT" VARCHAR2(20 BYTE), 
	"POSITION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JUNIT.EMPLOYEE
SET DEFINE OFF;
Insert into JUNIT.EMPLOYEE (CRMD,AMBIENT,POSITION) values ('crm0037','Java','MD');
Insert into JUNIT.EMPLOYEE (CRMD,AMBIENT,POSITION) values ('crm0040','.Net','JD');
Insert into JUNIT.EMPLOYEE (CRMD,AMBIENT,POSITION) values ('crm0041','.Net','SD');
Insert into JUNIT.EMPLOYEE (CRMD,AMBIENT,POSITION) values ('crm0042','Cobol','SD');
Insert into JUNIT.EMPLOYEE (CRMD,AMBIENT,POSITION) values ('crm0043','Cobol','JD');
Insert into JUNIT.EMPLOYEE (CRMD,AMBIENT,POSITION) values ('crm0033','Java','JD');
Insert into JUNIT.EMPLOYEE (CRMD,AMBIENT,POSITION) values ('crm0034','Java','SD');
Insert into JUNIT.EMPLOYEE (CRMD,AMBIENT,POSITION) values ('crm0035','Java','JD');
Insert into JUNIT.EMPLOYEE (CRMD,AMBIENT,POSITION) values ('crm0036','Java','AD');
Insert into JUNIT.EMPLOYEE (CRMD,AMBIENT,POSITION) values ('crm0044','Cobol','JD');
--------------------------------------------------------
--  DDL for Index SYS_C007281
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUNIT"."SYS_C007281" ON "JUNIT"."EMPLOYEE" ("CRMD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "JUNIT"."EMPLOYEE" ADD PRIMARY KEY ("CRMD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
