--------------------------------------------------------
--  File created - Monday-February-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SKILL_SET
--------------------------------------------------------

  CREATE TABLE "JUNIT"."SKILL_SET" 
   (	"CRMD" VARCHAR2(10 BYTE), 
	"SKILL_ID" NUMBER, 
	"ASSIGNED_DATE" DATE, 
	"ASSIGNEE_ID" VARCHAR2(10 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JUNIT.SKILL_SET
SET DEFINE OFF;
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0034',20,to_date('23-FEB-17','DD-MON-RR'),'crm0034',2);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0034',16,to_date('23-FEB-17','DD-MON-RR'),'crm0034',1);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0034',10,to_date('23-FEB-17','DD-MON-RR'),'crm0034',3);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0033',14,to_date('24-FEB-17','DD-MON-RR'),'crm0034',4);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0033',18,to_date('24-FEB-17','DD-MON-RR'),'crm0034',5);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0033',9,to_date('27-FEB-17','DD-MON-RR'),'crm0034',6);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0035',21,to_date('23-FEB-17','DD-MON-RR'),'crm0034',7);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0035',22,to_date('23-FEB-17','DD-MON-RR'),'crm0034',8);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0035',23,to_date('23-FEB-17','DD-MON-RR'),'crm0034',9);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0037',12,to_date('23-FEB-17','DD-MON-RR'),'crm0034',10);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0037',19,to_date('23-FEB-17','DD-MON-RR'),'crm0034',11);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0037',9,to_date('23-FEB-17','DD-MON-RR'),'crm0034',12);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0036',13,to_date('23-FEB-17','DD-MON-RR'),'crm0034',13);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0036',19,to_date('23-FEB-17','DD-MON-RR'),'crm0034',14);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0036',10,to_date('23-FEB-17','DD-MON-RR'),'crm0034',15);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0040',26,to_date('24-FEB-17','DD-MON-RR'),'crm0041',16);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0041',28,to_date('23-FEB-17','DD-MON-RR'),'crm0040',17);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0042',35,to_date('23-FEB-17','DD-MON-RR'),'crm0042',18);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0043',31,to_date('23-FEB-17','DD-MON-RR'),'crm0042',19);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0044',32,to_date('23-FEB-17','DD-MON-RR'),'crm0042',20);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0040',23,to_date('23-FEB-17','DD-MON-RR'),'crm0041',21);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0041',15,to_date('23-FEB-17','DD-MON-RR'),'crm0041',22);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0042',16,to_date('23-FEB-17','DD-MON-RR'),'crm0042',23);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0043',23,to_date('23-FEB-17','DD-MON-RR'),'crm0042',24);
Insert into JUNIT.SKILL_SET (CRMD,SKILL_ID,ASSIGNED_DATE,ASSIGNEE_ID,ID) values ('crm0043',12,to_date('23-FEB-17','DD-MON-RR'),'crm0042',25);
--------------------------------------------------------
--  DDL for Index SKILL_SET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUNIT"."SKILL_SET_PK" ON "JUNIT"."SKILL_SET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SKILL_SET
--------------------------------------------------------

  ALTER TABLE "JUNIT"."SKILL_SET" ADD CONSTRAINT "SKILL_SET_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JUNIT"."SKILL_SET" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JUNIT"."SKILL_SET" MODIFY ("SKILL_ID" NOT NULL ENABLE);
  ALTER TABLE "JUNIT"."SKILL_SET" MODIFY ("CRMD" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SKILL_SET
--------------------------------------------------------

  ALTER TABLE "JUNIT"."SKILL_SET" ADD CONSTRAINT "FK_EMPLOYEE" FOREIGN KEY ("CRMD")
	  REFERENCES "JUNIT"."EMPLOYEE" ("CRMD") ENABLE;
  ALTER TABLE "JUNIT"."SKILL_SET" ADD CONSTRAINT "FK_SKILL" FOREIGN KEY ("SKILL_ID")
	  REFERENCES "JUNIT"."SKILL" ("ID") ENABLE;
